name: Derniers épisodes du podcast
on:
 schedule:
   - cron: '0 0 * * 0' 
 workflow_dispatch: 
  jobs:
  update-readme-with-episodes:
   name: Update README with latest podcast episodes
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - uses: gautamkrishnar/blog-post-workflow@master
       with:
         feed_list: "https://anchor.fm/s/39f4fa04/podcast/rss"
